name: Tic-Tac-Toe Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-javascript:
    name: Test JavaScript code with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Jest
        run: npx jest tests
