name: Tic-Tac-Toe Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    name: Test Python code with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run pytest
        run: pytest tests
      
  test-javascript:
    name: Test JavaScript code with Jest
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - name: Install dependencies
        run: npm install
      
      - name: Run Jest
        run: npx jest tests
